Update dependency-review-vulnerable.yml

diff --git a/.github/workflows/dependency-review-vulnerable.yml b/.github/workflows/dependency-review-vulnerable.yml
--- a/.github/workflows/dependency-review-vulnerable.yml
+++ b/.github/workflows/dependency-review-vulnerable.yml
@@ -1,7 +1,11 @@
 name: ".NET Dependency Review and Vulnerable Packages"
-
-#on: pull_request
+env:
+  PROJECT_PATH: 'MinimalApis/MinimalApis.csproj'
+  
 on:
+  pull_request:
+    branches:
+      - main
   workflow_dispatch:
 
 jobs:
@@ -9,37 +13,54 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: "Checkout Repository"
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: "Dependency Review"
         uses: actions/dependency-review-action@v4
         with:
+          base-ref: 'main' # Or another branch name
+          head-ref: 'unit-test' # Or a specific commit SHA
           # Optional: Configure the action to your needs
-          allow-licenses: "MIT, Apache-2.0, BSD"
-          deny-licenses: "GPL-1.0, AGPL-3.0"
-          # Optional: Allows configuring which licenses are considered to be acceptable.
-          # allow-licenses: "MIT, Apache-2.0" 
-          # Optional: Specify a list of licenses that will cause the action to fail.
-          # deny-licenses: "GPL-1.0-or-later, AGPL-1.0-or-later"
-          fail-on-severity: 'critical' # Fails on critical vulnerabilities or higher
+          allow-licenses: MIT, Apache-2.0, BSD-3-Clause
+          # deny-licenses: GPL-1.0, AGPL-3.0
+          fail-on-severity: 'critical' # Possible values: "critical", "high", "moderate", "low"
+          fail-on-scopes: development, runtime # Possible values: "development", "runtime", "unknown"
+
+  vulnerable-packages:
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Checkout Repository"
+        uses: actions/checkout@v5
+
+      - name: "Setup .NET"
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '8.x'
+          cache: false
+
+      - name: "Scan for deprecated packages"
+        # run: dotnet list ${{ env.PROJECT_PATH }} package --deprecated
+        shell: bash
+        run: |
+          # Capture output and check for the presence of deprecated package headers
+          OUTPUT=$(dotnet list ${{ env.PROJECT_PATH }} package --deprecated)
+          echo "$OUTPUT"
           
-  # vulnerable-packages:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: "Checkout Repository"
-  #       uses: actions/checkout@v4
-
-  #     - name: "Setup .NET"
-  #       uses: actions/setup-dotnet@v4
-  #       with:
-  #         dotnet-version: '8.x' # Specify your .NET version
-  #         cache: false
-
-  #     - name: "Restore Dependencies"
-  #       run: dotnet restore
-
-  #     - name: "Check for Vulnerable Packages"
-  #       uses: actions/net-vulnerable@v2
-  #       with:
-  #         add-pr-comment: true # optional: configure to your needs
-  #         fail-on-vulnerable: true
+          if echo "$OUTPUT" | grep -q 'has the following deprecated packages'; then
+            echo "Error: Deprecated packages detected."
+            exit 0
+          fi
+   
+      - name: "Scan for vulnerable packages"
+        # run: dotnet list ${{ env.PROJECT_PATH }} package --vulnerable --include-transitive
+        run: |
+          OUTPUT=$(dotnet list ${{ env.PROJECT_PATH }} package --vulnerable --include-transitive)
+          echo "$OUTPUT"
+          
+          if echo "$OUTPUT" | grep -q 'has the following vulnerable packages'; then
+            echo "Error: vulnerable packages detected."
+            exit 1
+          else
+            echo "No vulnerable packages found."
+            exit 0
+          fi
